---
- name: install apt packages
  sudo: true
  with_items:
    - apache2
    - php5
    - php5-cli
    - php5-mongo
    - mongodb
  apt:
    name={{ item }}
    state=present
    update_cache=true

- name: download composer
  sudo: true
  get_url:
    url=http://getcomposer.org/composer.phar
    dest=/usr/bin/composer
    mode=777

- name: apache envvars
  sudo: true
  template:
    src=etc/apache2/envvars
    dest=/etc/apache2/envvars
  notify:
    - restart apache