---
- name: vhost
  sudo: true
  template:
    src=etc/apache2/sites-available/000-default.conf
    dest=/etc/apache2/sites-available/000-default.conf
  notify:
    - restart apache

- name: dependencies
  command:
    composer install --no-interaction
    chdir=/vagrant